import { describe, expect, it } from "vitest";
import { findMigration, loadMigrations, loadPrismaSchema } from "./schema-files.js";

/**
 * Conventions gate (spec: persistence / Schema data conventions — scenarios
 * "Conventions hold on new tables" and "Floating point money rejected").
 *
 * These checks parse the schema document and the migration SQL — the exact
 * artifacts `prisma migrate deploy` applies in CI. A live database is not
 * required: the DDL below was generated by Prisma itself from the schema, so
 * textual assertions on it are faithful to real database state.
 */

const SCHEMA = loadPrismaSchema();
const MIGRATIONS = loadMigrations();
const IDENTITY_SQL = findMigration(MIGRATIONS, "_staff_identity").sql;

interface ModelBlock {
  readonly name: string;
  readonly body: string;
}

function modelBlocks(schema: string): ModelBlock[] {
  const blocks: ModelBlock[] = [];
  const pattern = /model\s+(\w+)\s+\{([\s\S]*?)\n\}/g;

  for (const [, name, body] of schema.matchAll(pattern)) {
    blocks.push({ name, body });
  }

  expect(blocks.length).toBeGreaterThan(0);

  return blocks;
}

/** Scalar field lines (two-space indent, typed) inside a model block. */
function scalarFields(body: string): { name: string; line: string }[] {
  return body
    .split("\n")
    .map((line) => line.trim())
    .filter((line) =>
      /^[A-Za-z]\w*\s+(String|DateTime|Int|BigInt|Float|Decimal|Boolean|Json|Bytes)\b/.test(line)
    )
    .map((line) => ({ name: line.split(/\s+/)[0], line }));
}

describe("schema conventions (design D2)", () => {
  it("maps every model to snake_case and every multiword column via @map", () => {
    for (const block of modelBlocks(SCHEMA)) {
      expect(
        SCHEMA.includes(`@@map("${toSnake(block.name)}")`),
        `model ${block.name} must map to table ${toSnake(block.name)}`
      ).toBe(true);

      for (const field of scalarFields(block.body)) {
        if (isSnakeCase(field.name)) {
          continue;
        }
        expect(
          field.line.includes(`@map("${toSnake(field.name)}")`),
          `${block.name}.${field.name} must @map to ${toSnake(field.name)}`
        ).toBe(true);
      }
    }
  });

  it("uses UUID primary keys defaulted by gen_random_uuid() (shared-PK credential excepted)", () => {
    for (const block of modelBlocks(SCHEMA)) {
      const idLines = scalarFields(block.body).filter((field) => /@id\b/.test(field.line));
      expect(idLines.length, `${block.name} must declare exactly one @id field`).toBe(1);
      expect(idLines[0].line).toContain("@db.Uuid");

      // UserCredential shares its PK with user_profile by design decision:
      // the value is the parent's UUID, so no independent default exists.
      if (block.name !== "UserCredential") {
        expect(idLines[0].line, `${block.name}.id needs gen_random_uuid()`).toContain(
          '@default(dbgenerated("gen_random_uuid()"))'
        );
      }
    }
  });

  it("persists every DateTime as UTC timestamptz", () => {
    for (const block of modelBlocks(SCHEMA)) {
      for (const field of scalarFields(block.body)) {
        if (field.line.includes("DateTime")) {
          expect(field.line, `${block.name}.${field.name} must be @db.Timestamptz`).toContain(
            "@db.Timestamptz"
          );
        }
      }
    }
  });

  it("rejects floating point columns outright (money guard)", () => {
    expect(SCHEMA).not.toMatch(/\bFloat\b/);
    expect(IDENTITY_SQL + MIGRATIONS.map((m) => m.sql).join("\n")).not.toMatch(
      /\b(DOUBLE|REAL|FLOAT)\b/i
    );
  });

  it("keeps timestamps timezone-aware in migration DDL (no bare TIMESTAMP)", () => {
    // Catches both parameterized `TIMESTAMP(3)` and bare
    // `TIMESTAMP WITHOUT TIME ZONE` forms.
    expect(IDENTITY_SQL).not.toMatch(/\bTIMESTAMP(\s*\(|\s+WITHOUT\b)/i);
  });
});

describe("migration 001 · staff identity surface", () => {
  it("creates profile, credential, and session tables", () => {
    expect(IDENTITY_SQL.includes('CREATE TABLE "user_profile"')).toBe(true);
    expect(IDENTITY_SQL.includes('CREATE TABLE "user_credential"')).toBe(true);
    expect(IDENTITY_SQL.includes('CREATE TABLE "staff_session"')).toBe(true);
  });

  it("enforces global unique staff email", () => {
    expect(IDENTITY_SQL).toMatch(
      /CREATE UNIQUE INDEX "user_profile_email_key" ON "user_profile"\("email"\)/
    );
  });

  it("shares the credential primary key with its profile (join-free reads)", () => {
    expect(IDENTITY_SQL).toMatch(
      /CREATE TABLE "user_credential"[\s\S]*?CONSTRAINT "user_credential_pkey" PRIMARY KEY \("user_profile_id"\)/
    );
  });

  it("restricts credential deletion but cascades sessions with their profile", () => {
    expect(IDENTITY_SQL).toMatch(
      /ALTER TABLE "user_credential".*FOREIGN KEY \("user_profile_id"\) REFERENCES "user_profile"\("id"\) ON DELETE RESTRICT/
    );
    expect(IDENTITY_SQL).toMatch(
      /ALTER TABLE "staff_session".*FOREIGN KEY \("user_profile_id"\) REFERENCES "user_profile"\("id"\) ON DELETE CASCADE/
    );
  });

  it("indexes session lookup surfaces: token_hash unique, profile listing plain", () => {
    expect(IDENTITY_SQL).toMatch(/CREATE UNIQUE INDEX "staff_session_token_hash_key"/);
    expect(IDENTITY_SQL).toMatch(/CREATE INDEX "staff_session_user_profile_id_idx"/);
  });

  it("declares session expiry machinery per design D4", () => {
    expect(IDENTITY_SQL).toMatch(/"last_seen_at" TIMESTAMPTZ\(3\) NOT NULL/);
    expect(IDENTITY_SQL).toMatch(/"idle_expires_at" TIMESTAMPTZ\(3\) NOT NULL/);
    expect(IDENTITY_SQL).toMatch(/"absolute_expires_at" TIMESTAMPTZ\(3\) NOT NULL/);
    expect(IDENTITY_SQL).toMatch(/"revoked_at" TIMESTAMPTZ\(3\),/);
  });

  it("documents RESTRICTED password material in the applied artifact", () => {
    expect(IDENTITY_SQL).toMatch(/RESTRICTED/);
  });
});

function toSnake(name: string): string {
  return name.replaceAll(/([a-z0-9])([A-Z])/g, "$1_$2").toLowerCase();
}

function isSnakeCase(name: string): boolean {
  return /^[a-z][a-z0-9_]*$/.test(name);
}
